### ISSUE TITLE
Release 1.1.0 is shown as 1.0.3 after import

### ISSUE THREAD

**Issue by vx-i** [Orange-OpenSource/keepass-vault-sync-plugin#6]
Good morning, I imported the new release into Plugin folder, started KeePass, plugin was compiled, but it shows still version 1.0.3. Is it just wrong metadata, or even old release file?

**Comment by Karreg** [comment]
I did not have this issue, so I have cleaned my cache directory, re-downloaded the plgx file, and I have indeed reproduced your issue. I'll have a look.

**Comment by Karreg** [comment]
I have created version 1.1.1 to fix this issue for 1.0.3 and 1.1.0 version users. Let me know if this fixes your issue.

**Comment by vx-i** [comment]
It's working. Many thanks.
