### ISSUE TITLE
Plugin asks to update however it is already the latest

### ISSUE THREAD

**Issue by gjf** [Orange-OpenSource/keepass-vault-sync-plugin#7]
The plugin update check in KeePass shows an update for VaultSync:
![Безымянный](https://user-images.githubusercontent.com/322186/110430920-22262980-80be-11eb-9309-e28d1351a182.png)
At the same time the plugin already updated to the latest version published here.

**Comment by Karreg** [comment]
That was an issue with version 1.1.0 but it seems to be fixed with version 1.1.1 (see #6).
Can you make sure you have restarted your keepass?
If yes, can you delete your plugin cache folder and restart keepass? It's located in `C:\Users\<USER>\AppData\Local\KeePass\PluginCache`

**Comment by gjf** [comment]
Yeah redownloaded the plugin, cleared the cache and seems the issue is solved. Thank you!
